services:
  backend: # custome key name
  
    # image: python:alpine3.22
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
    env_file:
      - .env.sample

    volumes:
      - ./backend/src:/app
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild 
          path: backend/requirements.txt
        - action: rebuild 
          path: backend/Dockerfile
        - action: restart
          path: backend/src
  
#db_url = postgresql+psycopg://username:password@dbhost:dbport/dbname
#DATBASE_URL=postgresql+psycopg://dbuser:db-password@db_service:5432/mydb

  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb
    # env_file:
    #   - .env.sample-db
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data

  # static_html: # custome key name 
  #   # image: python:alpine3.22
  #   build:
  #     context: ./static_html
  #     dockerfile: static.Dockerfile
  #   ports:
  #     - 8000:8000
  #   command: python -m http.server 8000
  #   volumes:
  #     - ./static_html/src:/app

volumes:
  dc_managed_db_volume: 