name: Daily Curl Job

on:
  schedule:
    - cron: '52 20 * * *'  # Runs every day at 20:52 UTC = 3:52PM CDT

jobs:
  run-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Execute POST curl command
        run: |
          curl -X POST -d '{"message": "Research latest innovation in AI in last 24 hours and email me the results."}' \
          -H "Content-Type: application/json" \
          https://serene-eagerness-production.up.railway.app/api/chats/
